### ISSUE TITLE
Failure to load key

### ISSUE THREAD

**Issue by vicerious001** [TheGeneticsGuy/Guild-Roster-Manager#10]
Shortly after logging in to WoW, I get this message just after GRM finishes a sync:

GRM WARNING!!! FAILURE TO LOAD THIS KEY:
 PLEASE REPORT TO ADDON DEV! THANK YOU!

That's the whole message - nothing about which or what key, specifically, and BugSack didn't catch an error.

**Comment by TheGeneticsGuy** [comment]
Someone else reported this this week too. It's basically passing an empty
string for some reason like it never got loaded. If you ever find a way to
recreate it that'd be great because so far I have no idea the source as
that bug was theoretically not supposed to happen lol

**Comment by TheGeneticsGuy** [comment]
I am going to set this to Lua error if passed an empty string next update so I can at least get a trace on the source. Thanks for the report - I will push this in the next update. Closing this for now.

**Comment by TheGeneticsGuy** [comment]
Actually - would you be able to tell me if this happened on another language client than English you might have been using?

**Comment by vicerious001** [comment]
I only use the English client. But this error does seem to appear on every sync attempt.

**Comment by TheGeneticsGuy** [comment]
Ok I'll keep this open for now but let me know if you see it in the latest GRM build - and if sync is completing properly TY

**Comment by vicerious001** [comment]
I've gotten through a couple of syncs with my guildies now without seeing this message again.

**Comment by TheGeneticsGuy** [comment]
Ok great. Thanks! I'll close for now then. If it resurfaces let me know!
