### ISSUE TITLE
Discord invite links are invalid.

### ISSUE THREAD

**Issue by CharlesHunter** [TheGeneticsGuy/Guild-Roster-Manager#25]
I'm assuming this has something to do with the README doc being duplicated across all addon mirrors, but every site (curseforge, wowinterface, addonswow) has invalid discord invites.

**Comment by TheGeneticsGuy** [comment]
Hey, sorry to respond so late - not sure what addonswow is, my guess is the crawl wowinterface and curse. You're right though, I updated the discord links. I keep a limit on them to max uses at 100 to prevent the webcrawlers that grab your links and spam others for em. Limited use links strongly negates this kind of spam.

**Comment by TheGeneticsGuy** [comment]
Thanks again for reminding me to update these :D

**Comment by thedelk** [comment]
Any chance at another re-up? I can't find a good invite link.

**Comment by TheGeneticsGuy** [comment]
Here ya go i'll update them

**Comment by TheGeneticsGuy** [comment]
https://discord.gg/hKgBNmF
