### ISSUE TITLE
error in Classic

### ISSUE THREAD

**Issue by Daeveren** [TheGeneticsGuy/Guild-Roster-Manager#27]
Getting this error in Classic all of a sudden while being afk in Ironforge, perhaps some sync error, I thought it would be useful to report it here:

```
Message: ...AddOns\Guild_Roster_Manager\Guild_Roster_Manager-1.927.lua:7960: attempt to index local 'player' (a nil value)
Time: Sat Dec 19 20:13:30 2020
Count: 1
Stack: ...AddOns\Guild_Roster_Manager\Guild_Roster_Manager-1.927.lua:7960: attempt to index local 'player' (a nil value)
...erface\AddOns\Guild_Roster_Manager\GRM_GuildSync.lua:5817: in function <...erface\AddOns\Guild_Roster_Manager\GRM_GuildSync.lua:5470>

Locals: self = GRMsyncMessageTracking {
 0 = <userdata>
}
event = "CHAT_MSG_ADDON"
prefix = "GRM_SYNC"
msg = "Maxxie-PyrewoodVillage?false?1605381635"
channel = "GUILD"
sender = "Patronpala-PyrewoodVillage"
comms = <table> {
 versionCheckEpoch = 0
 abortSync = false
 prefix2 = "GRM_MAINSYNCUP"
 senderRankRequirement = 6
 senderRankID = 5
 isFound = true
}
```

**Comment by TheGeneticsGuy** [comment]
Hey @Daeveren Do you know if sync completed, and this error still popped, or if this caused the sync to fail? Thanks!

**Comment by Daeveren** [comment]
I don't remember if the sync finished, I know that once I've seen the error I've done a reloadui; it happened once more shortly after that, but since then, no error anymore. I guess this can be safely closed if you've inspected the error code and it's not clear why it happened. I'll make sure I come back if I see another error.

**Comment by Daeveren** [comment]
Got the errors again (atleast they seem to be the same error):

![image](https://user-images.githubusercontent.com/6321337/103175778-415e3a80-4875-11eb-8180-f352a51f6bcc.png)

```Message: ...AddOns\Guild_Roster_Manager\Guild_Roster_Manager-1.927.lua:7960: attempt to index local 'player' (a nil value)
Time: Sun Dec 27 18:52:54 2020
Count: 1
Stack: ...AddOns\Guild_Roster_Manager\Guild_Roster_Manager-1.927.lua:7960: attempt to index local 'player' (a nil value)
...erface\AddOns\Guild_Roster_Manager\GRM_GuildSync.lua:5817: in function <...erface\AddOns\Guild_Roster_Manager\GRM_GuildSync.lua:5470>

Locals: self = GRMsyncMessageTracking {
 0 = <userdata>
}
event = "CHAT_MSG_ADDON"
prefix = "GRM_SYNC"
msg = "Hared-PyrewoodVillage?false?1608095870"
channel = "GUILD"
sender = "Kiksen-PyrewoodVillage"
comms = <table> {
 versionCheckEpoch = 0
 abortSync = false
 prefix2 = "GRM_MAINSYNCUP"
 senderRankRequirement = 6
 senderRankID = 5
 isFound = true
}
```


```Message: ...AddOns\Guild_Roster_Manager\Guild_Roster_Manager-1.927.lua:7960: attempt to index local 'player' (a nil value)
Time: Sun Dec 27 18:55:33 2020
Count: 1
Stack: ...AddOns\Guild_Roster_Manager\Guild_Roster_Manager-1.927.lua:7960: attempt to index local 'player' (a nil value)

Locals: ```

**Comment by Daeveren** [comment]
Btw the Hared player whos name I see mentioned there is no longer in the guild.

**Comment by TheGeneticsGuy** [comment]
Ok this is very helpful. Thank you! I am working on something at the moment that is taking up a lot of my time, but I will make sure to get this resolved in the coming update.

**Comment by TheGeneticsGuy** [comment]
I can tell you what is happening though as I see it, code wise. Basically, for some reason, even though this player has quit their name has not yet been removed from the guild, but oddly, their alt data has. so it shows them as still existing, but then it tries to pull their alt data and it crashes out. This function becomes completely redundant in my next update though as I am rewriting the entire backend alt logic handling and sync protocol.

**Comment by Daeveren** [comment]
Awesome, thank you for your work!

**Comment by TheGeneticsGuy** [comment]
I basically ended up taking a year off - my pending update fixes this if it has not already. Sorry man I just forgot about this!
