### ISSUE TITLE
Transferring guild data to different server

### ISSUE THREAD

**Issue by dleblond312** [TheGeneticsGuy/Guild-Roster-Manager#28]
GRM is an amazing feature, and it contains the history of our guild since near-launch day of WoW Classic. I really love it for this and it's important to me as a guild and community leader. My guild is transferring servers, and I do not wish to lose that rich history. I'm wondering how I might manipulate Guild_Roster_Manager.lua to best preserve history between the transfer. Most characters have yet to transfer, so they are still active guild members.

Could I clone the data, change the server prefix and import it onto the new server? Do you foresee any issues with that? Alternatively, can I export and manipulate the data such that it could be imported again? Your help is greatly appreciated, and so is your add-on!

**Comment by TheGeneticsGuy** [comment]
Wow somehow this one slipped past me. I was basically inactive from WOW for a while. Hit me up on discord if you still want assistance as transferring with a save is pretty easy, just needs to be done manually. I am probably too late.
