### ISSUE TITLE
Wrath 3.4.1

### ISSUE THREAD

**Issue by ExpiredPepsi** [TheGeneticsGuy/Guild-Roster-Manager#34]
Hey, it looks like Wrath Classic 3.4.1 and the API update that came along with it broke GRM. I get these 4 errors on login/reload and nothing works, names aren't tagged in guild chat and the GRM guild roster pane doesn't show up when looking at a guildy.

> ```
> Message: bad argument #4 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
> Time: Tue Jan 17 22:51:54 2023
> Count: 1
> Stack: bad argument #4 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
> [string "=[C]"]: ?
> [string "=[C]"]: in function `CreateTexture'
> [string "@Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua"]:406: in function `?'
> [string "@Interface/AddOns/Guild_Roster_Manager/GRM_UI.lua"]:409: in main chunk
> Locals: (*temporary) = "bad argument #4 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))"
> ```

> ```
> Message: Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua:1106: attempt to call field 'GRM_MinimapButtonInit' (a nil value)
> Time: Tue Jan 17 22:51:58 2023
> Count: 1
> Stack: Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua:1106: attempt to call field 'GRM_MinimapButtonInit' (a nil value)
> [string "@Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua"]:146: in function <...tCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:144>
> [string "=[C]"]: in function `GRM_MinimapButtonInit'
> [string "@Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua"]:1106: in function `FinalSettingsConfigurations'
> [string "@Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua"]:1015: in function `LoadSettings'
> [string "@Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua"]:25585: in function `DataLoadDelayProtection'
> [string "@Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua"]:25576: in function <Interface/AddOns/Guild_Roster_Manager/GRM_Core.lua:25536\>
> Locals: private = <table> {
>  ThrowError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:46
>  DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:87
>  ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:107
>  SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:83
>  MAX_STACK_DEPTH = 10
>  log = <table> {
>  }
>  ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:116
>  IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:77
>  NewError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:50
>  IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:94
> }
> orig_errorhandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360
> ```

> ```
> Message: Interface/AddOns/Guild_Roster_Manager/GRM_UI.lua:1 (null)
> Time: Tue Jan 17 22:51:58 2023
> Count: 1
> ```

> ```
> Message: Interface_Wrath\FrameXML\Bindings.xml:1 Interface/AddOns/Guild_Roster_Manager/GRM_UI.lua:1 (null)
> Time: Tue Jan 17 22:51:58 2023
> Count: 1
> ```

**Comment by TheGeneticsGuy** [comment]
Thanks for the heads up! Looks like some UI API changes in new update.

**Comment by TheGeneticsGuy** [comment]
This is now fixed. Thanks for heads up!
