### ISSUE TITLE
GRM not released on github

### ISSUE THREAD

**Issue by nrb0** [TheGeneticsGuy/Guild-Roster-Manager#35]
Hello,

It looks like the latest version released on GitHub (R1.952) does not match the most recent one that is available on Curseforge (R1.953).

Would it be possible to publish this version as released on the repo as well so that WoWUp can pick it up ?

Many thanks !

**Comment by TheGeneticsGuy** [comment]
Ya sure - I kind of had another build I was working on my local GIT repository but I hadn't pushed a release public - I'll just bypass it and manually update here for you. Just a heads up - I do support WAGO, which wowup SHOULD pull from. But I can do from here as well.
