### ISSUE TITLE
GRM Lua Error..

### ISSUE THREAD

**Issue by jeske** [TheGeneticsGuy/Guild-Roster-Manager#41]
This is a GRM Lua error that threw with the latest build....

![image](https://github.com/TheGeneticsGuy/Guild-Roster-Manager/assets/15093/85629294-431e-4998-9b8a-eff4a09b547f)

**Comment by TheGeneticsGuy** [comment]
Ya, someone reported this on discord. It seems like it is happening when in combat when not in a guild. I'd just disable GRM when not in a guild until I get back to town. I won't be back home until Oct 18th. On vacation atm. Sorry about the bug, but thanks for the report!

**Comment by TheGeneticsGuy** [comment]
This is fixed in the update today! Sorry for the long delay - I got back from vacation and had trouble catching up on everything in RL, let alone the addon lol. All is good now!

**Comment by TheGeneticsGuy** [comment]
All finished
