### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by TrueBrujah** [TheGeneticsGuy/Guild-Roster-Manager#42]
Message: ...Ons/AddOnSkins/Skins/AddOns/Guild_Roster_Manager.lua:568: attempt to index global 'GuildFrame' (a nil value)
Time: Sat Jun  1 05:53:35 2024
Count: 4
Stack: ...Ons/AddOnSkins/Skins/AddOns/Guild_Roster_Manager.lua:568: attempt to index global 'GuildFrame' (a nil value)

Locals:

**Comment by TheGeneticsGuy** [comment]
Unfortunately, I can't really control the release of what AddOnSkins developer puts out. He has not updated his addon for a long time and has a very outdated version of the addon skins template for GRM. As you can see [right here](https://github.com/Azilroka/AddOnSkins/pulls), he has not updated GRM from my pull request from forever ago, and the addon is largely abandoned with only a cursory update here and there where he might change the release version.

If you want to get a more up-to-date version of the GRM skin you will ultimately need to download it manually for addonskins and copy it over into the folder. You can [find it right here](https://github.com/TheGeneticsGuy/Guild_Roster_Manager_AddonSkinsFile)

**Comment by TheGeneticsGuy** [comment]
Let me know if that works for you. TY.
