### ISSUE TITLE
GRM broken on classic Era/SoD due to UI update from Blizzard

### ISSUE THREAD

**Issue by Cyoor** [TheGeneticsGuy/Guild-Roster-Manager#43]
As of the 1.15.3 the blizzard UI changed.
This has caused the addon to stop working.

**Comment by TheGeneticsGuy** [comment]
Ya, I will have an update for this soon - This was a little bigger of an update than I anticipated as I didn't realize Blizz was going to integrate the new communities/guild interface from retail into Classic!

**Comment by Cyoor** [comment]
Thanks for your work! <3

**Comment by Cyoor** [comment]
Any time estimation for this?

**Comment by TheGeneticsGuy** [comment]
@Cyoor hey, sorry about the long delay - the release is out now :)

**Comment by Cyoor** [comment]
Thanks a lot!
