### ISSUE TITLE
Got this error today on the latest version

### ISSUE THREAD

**Issue by yajinni** [TheGeneticsGuy/Guild-Roster-Manager#47]
3x Guild_Roster_Manager/GRM_Stats.lua:59: attempt to compare number with nil
[string "@Guild_Roster_Manager/GRM_Stats.lua"]:59: in function `TriggerProgressBar'
[string "@Guild_Roster_Manager/GRM_GuildSync.lua"]:6733: in function <Guild_Roster_Manager/GRM_GuildSync.lua:6495>

Locals:
progressBar = GRM_SyncProgressBar {
 BottomLeftCorner = Texture {
 }
 Hold = false
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 GRM_SyncProgressBarTexture = Texture {
 }
 killSwitch = false
 TopRightCorner = Texture {
 }
 StartTime = 1722530374
 colorOnComplete = <table> {
 }
 Percent = 0
 RemainingTime = 0
 TopEdge = Texture {
 }
 Timer = 0
 GRM_SyncProgressBarText = FontString {
 }
 Center = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
destinationNumber = 100
timeToProgress = nil
colorOnComplete = nil
hold = nil
loopDelay = 0.100000
num = 0
ascending = true
progressBarTexture = Texture {
 PixelSnapDisabled = true
}
progressBarText = FontString {
}
barWidth = 304.999969
t = 0
(*temporary) = 304.999969
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Comment by Cyoor** [comment]
Can confirm also getting this

**Comment by TheGeneticsGuy** [comment]
Sorry for the late response - just noticed this. This is resolved in latest build
