### ISSUE TITLE
errors when loading into game

### ISSUE THREAD

**Issue by Vettic** [TheGeneticsGuy/Guild-Roster-Manager#48]
Bug sack catches 2 errors while loading into the game

**Error 1**
1x Guild_Roster_Manager/GRM_HC.lua:27: attempt to call field 'IsHardcoreActive' (a nil value)
[string "@Guild_Roster_Manager/GRM_HC.lua"]:27: in function `HardCoreInitialize'
[string "@Guild_Roster_Manager/GRM_HC.lua"]:401: in main chunk

Locals:
region = <table> {
 ptBR = "MortesHardcore"
 ruRU = "ГероическиеСмерти"
 deDE = "HardcoreTode"
 koKR = "하드코어"
 esMX = "MuertesEnExtremo"
 enUS = "HardcoreDeaths"
 zhTW = "專家模式玩家死亡"
 zhCN = "专家死亡"
 esES = "MuertesHardcore"
 frFR = "Morts"
}
(*temporary) = nil
(*temporary) = "attempt to call field 'IsHardcoreActive' (a nil value)"
GRM_HC = <table> {
 deathEvent = Frame {
 }
}

**Error 2**
1x Guild_Roster_Manager/GRM_Core.lua:27088: attempt to call field 'IsHardcoreActive' (a nil value)
[string "@Guild_Roster_Manager/GRM_Core.lua"]:27088: in function `SettingsLoadedFinishDataLoad'
[string "@Guild_Roster_Manager/GRM_Core.lua"]:1413: in function <Guild_Roster_Manager/GRM_Core.lua:1372>

Locals:
langIndex = 1
(*temporary) = nil
(*temporary) = "attempt to call field 'IsHardcoreActive' (a nil value)"

**Comment by TheGeneticsGuy** [comment]
Sorry just noticed this. Be sure to grab the latest 1.9912 build - this is not any issue anymore.
