### ISSUE TITLE
Name OR not Name; This is the question

### ISSUE THREAD

**Issue by SirHesti** [TheGeneticsGuy/Guild-Roster-Manager#5]
Hallo,

I am use GRML since 4 month (Classic-Lakeshire-Europe). Now I have create a new guild member and now every minute GRML means, he has just turn in into the guild. The problem comes, i think, is the name of the new guild member. It is the same as the guild. both are freidenker in one word.

sincerely Hesti

**Comment by TheGeneticsGuy** [comment]
Ya it is resolved in next build. Disable scanning the log for changes til
then to avoid spam.GRM > Options > scan tab.

Thanks!
