### ISSUE TITLE
Error on load, WoW Classic build = 40400, GRM build = R1.99134

### ISSUE THREAD

**Issue by godsyn** [TheGeneticsGuy/Guild-Roster-Manager#50]
Error on load, WoW Classic build = 40400, GRM build = R1.99134
```
Guild_Roster_Manager/GRM_Patches.lua:8985: attempt to index field '?' (a nil value)
[string "@Guild_Roster_Manager/GRM_Patches.lua"]:8985: in function `?'
[string "@Guild_Roster_Manager/GRM_Patches.lua"]:1625: in function `SettingsCheck'
[string "@Guild_Roster_Manager/GRM_Core.lua"]:1427: in function `LoadSettings'
[string "@Guild_Roster_Manager/GRM_Core.lua"]:28899: in function `DataLoadDelayProtection'
[string "@Guild_Roster_Manager/GRM_Core.lua"]:28872: in function <Guild_Roster_Manager/GRM_Core.lua:28853>
```

**Comment by TheGeneticsGuy** [comment]
Ok thanks. Ya, someone reported this on github too. It's failing to patch properly so GRM won't even load for you. I believe I already wrote a fix for it, but I gotta confirm if someone can test it. There COULD be more than 1 issue given this bug, but because this scripting language causes all downstream actions to fail once this fails, it might be masking downstream bugs. Any chance you can send me a copy of your Saved Variables file? That way I could guarantee my update I hopefully drop later today fixes it.

**Comment by TheGeneticsGuy** [comment]
You can find the file here:

`\WTF\Account\9999999#9\SavedVariables\Guild_Roster_Manager.lua`

**Comment by godsyn** [comment]
[Guild_Roster_Manager.zip](https://github.com/user-attachments/files/16801749/Guild_Roster_Manager.zip)
LUA wasn't supported, so I zipped it.

**Comment by TheGeneticsGuy** [comment]
Awesome thank you! I probably won't get it to it til tonight, but I should get a fix done pretty quick. Thanks!

**Comment by godsyn** [comment]
Dude, take your time. It isn't game breaking, just an error on load. Thanks
so much for taking the time to make such an awesome addon.
Honestly all I use it for is alt-identification. I know of no other addon
that handles other's alts, and it is much appreciated.

**Comment by TheGeneticsGuy** [comment]
Haha no worries. This is my main hobby and I enjoy building addons probably more than I enjoy playing the game. I will get the fix out soon. Just a matter of getting on my PC with time to get it updated. Thursday nights are busy cause of kids, soccer practice, etc... so depending on what my wife wants to do after they go to bed will determine if I get this done tonight, or tomorrow as i don't work on  Fridays but she does lol.

**Comment by TheGeneticsGuy** [comment]
Ok just a heads up - the pending release will have this fixed. I will have it out overnight - just doing a couple last minute requests from discord and I'll drop it.

**Comment by TheGeneticsGuy** [comment]
This is now fixed in current build. TY AGAIN FOR THE REPORT! :)

**Comment by godsyn** [comment]
Confirmed resolved. Thank you for the fix.
