### ISSUE TITLE
[Feature Request] Add Realm to export fields

### ISSUE THREAD

**Issue by waggz81** [TheGeneticsGuy/Guild-Roster-Manager#51]
Now that cross realm guilds are a thing, it would be helpful to include the realm of the character as a field option in the member export tool.

**Comment by TheGeneticsGuy** [comment]
Hey cool idea. I like it! Standby

**Comment by TheGeneticsGuy** [comment]
@waggz81 This has been added in the latest build. You'll see it near the tail end of the options by the GUID export.

One of these days I want to clean up the export window, it's just not priority, and I keep adding things to it lol. I think I'll eventually rebuild it with customizable order.

Thanks again for the suggestion!
