### ISSUE TITLE
Click or Press TAB to cycle through each step

### ISSUE THREAD

**Issue by Iowerth** [TheGeneticsGuy/Guild-Roster-Manager#52]
Hi. Cata Classic. Addon v.1.99141.
Every time I log in I see this:
![1](https://github.com/user-attachments/assets/e529146c-bef5-41ee-b0db-1fa180e35f4b)

In English - GRM WARNING!!! FAILURE TO LOAD THIS KEY: {name}\nPLEASE REPORT TO ADDON DEV! THANK YOU!

How to fix?

**Comment by TheGeneticsGuy** [comment]
Oh hey sorry for the late response.  This got fixed a few patches back... Somehow just noticed as I was out of town for a few weeks.
