### ISSUE TITLE
Lua Error at load with latest

### ISSUE THREAD

**Issue by Motowatch** [TheGeneticsGuy/Guild-Roster-Manager#56]
Date: 2024-10-01 16:35:26
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Guild_Roster_Manager/GRM_UI_API.lua line 617:
   attempt to index field '?' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Guild_Roster_Manager/GRM_UI_API.lua"]:617: CreateOptionsSlider()
   [string "@Interface/AddOns/Guild_Roster_Manager/GRM_Roster.lua"]:291: BuildRosterFrames()
   [string "@Interface/AddOns/Guild_Roster_Manager/GRM_UI.lua"]:5889: ?()
   [string "@Interface/AddOns/Guild_Roster_Manager/GRM_UI.lua"]:18883: in main chunk
Locals:

**Comment by TheGeneticsGuy** [comment]
This has been fixed and was related to the 11.0.2 update in loading outdated addon as it was not adapted yet.
