### ISSUE TITLE
Question on still existing previous release-versions

### ISSUE THREAD

**Issue by Kabulla** [TheGeneticsGuy/Guild-Roster-Manager#57]
First of all:

Special thanx to all of you maintaining an caring for this great piece of art-addon. loved it for years, still do!

Question:
Would I still be able to find a version compatible to Game-Version 3.3.5 or slightly older?

Sorry for the bother and keep up the work you do!

Kabulla

**Comment by TheGeneticsGuy** [comment]
This will not be possible as this addon didn't exist until Legion 7.0+, and there are no old versions of the addon compatible with the outdated API. I do not have plans for trying to add support for private servers. Sorry.
