### ISSUE TITLE
Edit in bulk the join date of players

### ISSUE THREAD

**Issue by Graxo** [TheGeneticsGuy/Guild-Roster-Manager#58]
Hi, im looking for a way in Classic Era (Fresh servers) to bulk update the join date. I created a new guild and started inviting people. Then i found this addon but i dont want to enter the join date by hand in everyone's note.

**Comment by TheGeneticsGuy** [comment]
To mass update the dates of all players who don't have join dates set, use this API:

`/run GRM_API.SetAllUnknownJoinDates(26,11,2024)`

This will set all players without join dates, for example, to 26-11-2024. Be sure to enable in the /grm > options > officer Tab if you wish it to add the join dates to player's note.
