### ISSUE TITLE
Overwriting macros-cache.txt and removing existing 'General' macros

### ISSUE THREAD

**Issue by Blunkers** [TheGeneticsGuy/Guild-Roster-Manager#6]
Started having the issue where my C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\[ACCOUNTNAME] macros-cache file is being overwritten on start up, with this being the only content of said file after the fact:

VER 3 0000000000000001 "GRM_Tool" "INV_MISC_QUESTIONMARK"
END

Seems like a bit of a smoking gun to me.  I enjoy this useful addon but please stop overwriting all of my general macros.

**Comment by TheGeneticsGuy** [comment]
GRM is not overwriting all of your macros. GRM is creating and using just the macro "GRM_Tool" - I would suggest disabling all addons and just using GRM so you can verify for yourself. This macro is important to take advantage of the /grm macro tool. It is absolutely 100% NOT overwriting any other macros.

What likely happened is for some reason your file was lost on that PC (as in Classic macros are stored locally unlike server in retail), and then your next session with GRM it noticed there was no macro set so GRM set the one macro it uses "GRM_Tool" - the GRM addon is not capable of removing your other macros. It is not built anywhere into the code to do so.
